%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/iron/.*$
%global __requires_exclude_from ^/opt/ros/iron/.*$

Name:           ros-iron-opennav-coverage-demo
Version:        0.0.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS opennav_coverage_demo package

License:        Apache-2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-iron-nav2-bringup
Requires:       ros-iron-nav2-util
Requires:       ros-iron-opennav-coverage
Requires:       ros-iron-opennav-coverage-bt
Requires:       ros-iron-opennav-coverage-msgs
Requires:       ros-iron-opennav-coverage-navigator
Requires:       ros-iron-opennav-row-coverage
Requires:       ros-iron-rclcpp
Requires:       ros-iron-rclcpp-action
Requires:       ros-iron-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-iron-nav2-bringup
BuildRequires:  ros-iron-nav2-util
BuildRequires:  ros-iron-opennav-coverage
BuildRequires:  ros-iron-opennav-coverage-bt
BuildRequires:  ros-iron-opennav-coverage-msgs
BuildRequires:  ros-iron-opennav-coverage-navigator
BuildRequires:  ros-iron-opennav-row-coverage
BuildRequires:  ros-iron-rclcpp
BuildRequires:  ros-iron-rclcpp-action
BuildRequires:  ros-iron-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-iron-ament-lint-auto
BuildRequires:  ros-iron-ament-lint-common
%endif

%description
A demo using the Coverage Server, BT Nodes, and Coverage Navigator

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/iron"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/iron

%changelog
* Tue Jan 23 2024 Steve Macenski <steve@opennav.org> - 0.0.1-1
- Autogenerated by Bloom

